In [6]:
import sys
!"{sys.executable}" -m pip install xgboost
!"{sys.executable}" -m pip install optuna

Requirement already satisfied: xgboost in c:\users\yosua triantara\appdata\local\programs\python\python313\lib\site-packages (3.3.0)
Requirement already satisfied: numpy in c:\users\yosua triantara\appdata\local\programs\python\python313\lib\site-packages (from xgboost) (2.2.6)
Requirement already satisfied: scipy in c:\users\yosua triantara\appdata\local\programs\python\python313\lib\site-packages (from xgboost) (1.16.1)

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: optuna in c:\users\yosua triantara\appdata\local\programs\python\python313\lib\site-packages (4.9.0)
Requirement already satisfied: alembic>=1.5.0 in c:\users\yosua triantara\appdata\local\programs\python\python313\lib\site-packages (from optuna) (1.18.5)
Requirement already satisfied: colorlog in c:\users\yosua triantara\appdata\local\programs\python\python313\lib\site-packages (from optuna) (6.10.1)
Requirement already satisfied: numpy in c:\users\yosua triantara\appdata\local\programs\python\python313\lib\site-packages (from optuna) (2.2.6)
Requirement already satisfied: packaging>=20.0 in c:\users\yosua triantara\appdata\local\programs\python\python313\lib\site-packages (from optuna) (25.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in c:\users\yosua triantara\appdata\local\programs\python\python313\lib\site-packages (from optuna) (2.0.51)
Requirement already satisfied: tqdm in c:\users\yosua triantara\appdata\local\programs\python\python313\lib\site-packages (from optuna) (4.67.1)
Requirement already satisfied: PyYAML in c:\users\yosua triantara\appdata\local\programs\python\python313\lib\site-packages (from optuna) (6.0.2)
Requirement already satisfied: Mako in c:\users\yosua triantara\appdata\local\programs\python\python313\lib\site-packages (from alembic>=1.5.0->optuna) (1.3.12)
Requirement already satisfied: typing-extensions>=4.12 in c:\users\yosua triantara\appdata\local\programs\python\python313\lib\site-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: greenlet>=1 in c:\users\yosua triantara\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy>=1.4.2->optuna) (3.5.3)
Requirement already satisfied: colorama in c:\users\yosua triantara\appdata\local\programs\python\python313\lib\site-packages (from colorlog->optuna) (0.4.6)
Requirement already satisfied: MarkupSafe>=0.9.2 in c:\users\yosua triantara\appdata\local\programs\python\python313\lib\site-packages (from Mako->alembic>=1.5.0->optuna) (3.0.2)

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [7]:
import os
import joblib
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from xgboost import XGBRegressor

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

import optuna
from sklearn.metrics import mean_squared_error

In [8]:
data = np.load("../artifacts/dataset_sequences.npz")

X_train = data["X_train"]
X_val   = data["X_val"]
X_test  = data["X_test"]

print(X_train.shape)
print(X_val.shape)
print(X_test.shape)

(216981, 24, 36)
(43963, 24, 36)
(28428, 24, 36)

In [9]:
pred = np.load("../artifacts/lstm_predictions.npz")

y_train_true = pred["y_train_true"]
y_val_true   = pred["y_val_true"]
y_test_true  = pred["y_test_true"]

y_train_pred = pred["y_train_pred"]
y_val_pred   = pred["y_val_pred"]
y_test_pred  = pred["y_test_pred"]

residual_train = pred["residual_train"]
residual_val   = pred["residual_val"]
residual_test  = pred["residual_test"]

In [10]:
# Ambil feature pada timestep terakhir dari setiap window
X_train_xgb = X_train[:, -1, :]
X_val_xgb   = X_val[:, -1, :]
X_test_xgb  = X_test[:, -1, :]

print("Shape sebelum tambah prediksi LSTM:")
print(X_train_xgb.shape)
print(X_val_xgb.shape)
print(X_test_xgb.shape)

Shape sebelum tambah prediksi LSTM:
(216981, 36)
(43963, 36)
(28428, 36)

In [11]:
# Tambahkan prediksi LSTM sebagai feature tambahan
X_train_xgb = np.hstack([
    X_train_xgb,
    y_train_pred.reshape(-1, 1)
])

X_val_xgb = np.hstack([
    X_val_xgb,
    y_val_pred.reshape(-1, 1)
])

X_test_xgb = np.hstack([
    X_test_xgb,
    y_test_pred.reshape(-1, 1)
])

print("Shape akhir:")
print(X_train_xgb.shape)
print(X_val_xgb.shape)
print(X_test_xgb.shape)

Shape akhir:
(216981, 37)
(43963, 37)
(28428, 37)

In [12]:
os.makedirs("../models", exist_ok=True)

In [13]:
xgb_model = XGBRegressor(
    objective="reg:squarederror",
    n_estimators=300,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    n_jobs=-1
)

xgb_model.fit(
    X_train_xgb,
    residual_train
)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8, device=None, early_stopping_rounds=None,
             enable_categorical=True, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=300,
             n_jobs=-1, num_parallel_tree=None, ...)

In [14]:
train_residual_pred = xgb_model.predict(X_train_xgb)
val_residual_pred = xgb_model.predict(X_val_xgb)
test_residual_pred = xgb_model.predict(X_test_xgb)

In [15]:
train_final = y_train_pred.ravel() + train_residual_pred
val_final = y_val_pred.ravel() + val_residual_pred
test_final = y_test_pred.ravel() + test_residual_pred

In [16]:
def evaluate(y_true, y_pred):
    mae = mean_absolute_error(y_true, y_pred)
    mse = mean_squared_error(y_true, y_pred)
    rmse = np.sqrt(mse)
    nrmse = rmse / (np.max(y_true) - np.min(y_true))
    r2 = r2_score(y_true, y_pred)
    return {
        "MAE": mae,
        "MSE": mse,
        "RMSE": rmse,
        "NRMSE": nrmse,
        "R2": r2
    }

In [17]:
train_metrics = evaluate(y_train_true, train_final)
val_metrics = evaluate(y_val_true, val_final)
test_metrics = evaluate(y_test_true, test_final)
results = pd.DataFrame(
    [train_metrics, val_metrics, test_metrics],
    index=["Train", "Validation", "Test"]
)
results

                 MAE        MSE      RMSE     NRMSE        R2
Train       2.837082  31.673278  5.627902  0.005396  0.995736
Validation  2.604982  32.259837  5.679774  0.008619  0.994277
Test        2.431621  23.942780  4.893136  0.008350  0.987781

In [18]:
lstm_results = pd.read_csv(
    "../models/lstm_evaluation.csv",
    index_col=0
)

lstm_results

                 MAE        MSE      RMSE     NRMSE        R²
Train       3.210650  50.317642  7.093493  0.006801  0.993226
Validation  2.725367  32.782827  5.725629  0.008688  0.994184
Test        2.504920  23.959700  4.894865  0.008353  0.987772

In [19]:
lstm_results = lstm_results.rename(columns={"R2": "R²"})
results = results.rename(columns={"R2": "R²"})

In [20]:
comparison = pd.DataFrame({
    "LSTM": lstm_results.loc["Test"],
    "LSTM + XGBoost": results.loc["Test"]
}).T

comparison

                     MAE       MSE      RMSE     NRMSE        R²
LSTM            2.504920  23.95970  4.894865  0.008353  0.987772
LSTM + XGBoost  2.431621  23.94278  4.893136  0.008350  0.987781

In [21]:
mae_improvement = (
    (lstm_results.loc["Test", "MAE"] - results.loc["Test", "MAE"])
    / lstm_results.loc["Test", "MAE"]
) * 100

rmse_improvement = (
    (lstm_results.loc["Test", "RMSE"] - results.loc["Test", "RMSE"])
    / lstm_results.loc["Test", "RMSE"]
) * 100

r2_improvement = (
    (results.loc["Test", "R²"] - lstm_results.loc["Test", "R²"])
    / abs(lstm_results.loc["Test", "R²"])
) * 100

print(f"Improvement MAE  : {mae_improvement:.2f}%")
print(f"Improvement RMSE : {rmse_improvement:.2f}%")
print(f"Improvement R²   : {r2_improvement:.2f}%")

Improvement MAE  : 2.93%
Improvement RMSE : 0.04%
Improvement R²   : 0.00%

### Optuna Study

In [ ]:
def objective(trial):

    params = {

        "objective": "reg:squarederror",

        "n_estimators": trial.suggest_int(
            "n_estimators",
            100,
            1000
        ),

        "learning_rate": trial.suggest_float(
            "learning_rate",
            0.01,
            0.3,
            log=True
        ),

        "max_depth": trial.suggest_int(
            "max_depth",
            3,
            10
        ),

        "subsample": trial.suggest_float(
            "subsample",
            0.6,
            1.0
        ),

        "colsample_bytree": trial.suggest_float(
            "colsample_bytree",
            0.6,
            1.0
        ),

        "min_child_weight": trial.suggest_int(
            "min_child_weight",
            1,
            10
        ),

        "gamma": trial.suggest_float(
            "gamma",
            0,
            5
        ),

        "random_state": 42,

        "n_jobs": -1

    }

    model = XGBRegressor(**params)
    model.fit(

        X_train_xgb,

        residual_train

    )

    pred = model.predict(
        X_val_xgb
    )

    rmse = np.sqrt(

        mean_squared_error(

            residual_val,

            pred

        )

    )

    return rmse

In [23]:
def save_checkpoint(study, trial):

    joblib.dump(
        study,
        "../models/optuna_study.pkl"
    )

    study.trials_dataframe().to_csv(
        "../models/optuna_trials.csv",
        index=False
    )

In [24]:
study = optuna.create_study(
    direction="minimize"
)

study.optimize(
    objective,
    n_trials=50,
    callbacks=[save_checkpoint]
)

[I 2026-06-27 09:17:40,344] A new study created in memory with name: no-name-2b013ce5-5007-4dab-8b35-15a59abc2102
[I 2026-06-27 09:17:41,827] Trial 0 finished with value: 5.861307487340317 and parameters: {'n_estimators': 265, 'learning_rate': 0.24196639340396564, 'max_depth': 4, 'subsample': 0.9666175570087145, 'colsample_bytree': 0.7403442003328886, 'min_child_weight': 4, 'gamma': 1.8916321106892697}. Best is trial 0 with value: 5.861307487340317.
[I 2026-06-27 09:17:47,243] Trial 1 finished with value: 5.682330404831871 and parameters: {'n_estimators': 744, 'learning_rate': 0.015567351927421393, 'max_depth': 6, 'subsample': 0.8793363467109574, 'colsample_bytree': 0.6857822113414558, 'min_child_weight': 5, 'gamma': 3.1763991774148117}. Best is trial 1 with value: 5.682330404831871.
[I 2026-06-27 09:17:49,005] Trial 2 finished with value: 5.87490973256542 and parameters: {'n_estimators': 216, 'learning_rate': 0.2717196207631583, 'max_depth': 6, 'subsample': 0.7772777175718735, 'colsample_bytree': 0.9326546562370746, 'min_child_weight': 9, 'gamma': 4.6791618880157015}. Best is trial 1 with value: 5.682330404831871.
[I 2026-06-27 09:17:50,981] Trial 3 finished with value: 5.648585117213473 and parameters: {'n_estimators': 185, 'learning_rate': 0.10035812933980748, 'max_depth': 8, 'subsample': 0.8013084911420659, 'colsample_bytree': 0.9853025632709413, 'min_child_weight': 7, 'gamma': 3.5461932187909158}. Best is trial 3 with value: 5.648585117213473.
[I 2026-06-27 09:17:54,255] Trial 4 finished with value: 5.762513746308445 and parameters: {'n_estimators': 389, 'learning_rate': 0.10509211281135764, 'max_depth': 7, 'subsample': 0.846865627955817, 'colsample_bytree': 0.6729969906995208, 'min_child_weight': 5, 'gamma': 2.0047016727578053}. Best is trial 3 with value: 5.648585117213473.
[I 2026-06-27 09:17:58,646] Trial 5 finished with value: 5.692910309384374 and parameters: {'n_estimators': 374, 'learning_rate': 0.02209283586318253, 'max_depth': 8, 'subsample': 0.699086633343812, 'colsample_bytree': 0.988010835203738, 'min_child_weight': 1, 'gamma': 3.8870908196348672}. Best is trial 3 with value: 5.648585117213473.
[I 2026-06-27 09:18:06,003] Trial 6 finished with value: 5.649255958786019 and parameters: {'n_estimators': 974, 'learning_rate': 0.07483435657683042, 'max_depth': 7, 'subsample': 0.8857602994459574, 'colsample_bytree': 0.6654883319697334, 'min_child_weight': 10, 'gamma': 3.4296755323731216}. Best is trial 3 with value: 5.648585117213473.
[I 2026-06-27 09:18:12,817] Trial 7 finished with value: 5.692328389093696 and parameters: {'n_estimators': 939, 'learning_rate': 0.07580543958309326, 'max_depth': 7, 'subsample': 0.9713993230125941, 'colsample_bytree': 0.9673818225176618, 'min_child_weight': 10, 'gamma': 3.09738651519086}. Best is trial 3 with value: 5.648585117213473.
[I 2026-06-27 09:18:14,379] Trial 8 finished with value: 5.709781172612888 and parameters: {'n_estimators': 259, 'learning_rate': 0.0264208919704412, 'max_depth': 3, 'subsample': 0.950305528410662, 'colsample_bytree': 0.6798325492777526, 'min_child_weight': 8, 'gamma': 3.1593837717484705}. Best is trial 3 with value: 5.648585117213473.
[I 2026-06-27 09:18:18,323] Trial 9 finished with value: 5.725593538045992 and parameters: {'n_estimators': 484, 'learning_rate': 0.052023926430173034, 'max_depth': 7, 'subsample': 0.7634708198022759, 'colsample_bytree': 0.9505170690234869, 'min_child_weight': 6, 'gamma': 3.077127484062634}. Best is trial 3 with value: 5.648585117213473.
[I 2026-06-27 09:18:30,575] Trial 10 finished with value: 5.6116268012458965 and parameters: {'n_estimators': 662, 'learning_rate': 0.01061977552142729, 'max_depth': 10, 'subsample': 0.6108280003476435, 'colsample_bytree': 0.8458291694196574, 'min_child_weight': 1, 'gamma': 0.3918418533758796}. Best is trial 10 with value: 5.6116268012458965.
[I 2026-06-27 09:18:43,960] Trial 11 finished with value: 5.653186178539283 and parameters: {'n_estimators': 625, 'learning_rate': 0.03909150856282561, 'max_depth': 10, 'subsample': 0.6104206592872342, 'colsample_bytree': 0.8481826994878015, 'min_child_weight': 1, 'gamma': 0.060011490030589365}. Best is trial 10 with value: 5.6116268012458965.
[I 2026-06-27 09:18:45,956] Trial 12 finished with value: 5.644558488330598 and parameters: {'n_estimators': 123, 'learning_rate': 0.01195165725758551, 'max_depth': 10, 'subsample': 0.6258504717529358, 'colsample_bytree': 0.8150708216305163, 'min_child_weight': 3, 'gamma': 0.6809717467309597}. Best is trial 10 with value: 5.6116268012458965.
[I 2026-06-27 09:18:57,600] Trial 13 finished with value: 5.630939699996037 and parameters: {'n_estimators': 762, 'learning_rate': 0.01007286558940984, 'max_depth': 10, 'subsample': 0.6013245559546261, 'colsample_bytree': 0.8041045711254794, 'min_child_weight': 3, 'gamma': 0.20873631051521727}. Best is trial 10 with value: 5.6116268012458965.
[I 2026-06-27 09:19:07,892] Trial 14 finished with value: 5.630719559881938 and parameters: {'n_estimators': 775, 'learning_rate': 0.010393840660329126, 'max_depth': 9, 'subsample': 0.6711046426669909, 'colsample_bytree': 0.8394940313433749, 'min_child_weight': 2, 'gamma': 0.89526711053715}. Best is trial 10 with value: 5.6116268012458965.
[I 2026-06-27 09:19:18,743] Trial 15 finished with value: 5.644346343717558 and parameters: {'n_estimators': 789, 'learning_rate': 0.01740686032353961, 'max_depth': 9, 'subsample': 0.6810449067914034, 'colsample_bytree': 0.8830041970990626, 'min_child_weight': 2, 'gamma': 1.1133698556466929}. Best is trial 10 with value: 5.6116268012458965.
[I 2026-06-27 09:19:27,554] Trial 16 finished with value: 5.619739726732116 and parameters: {'n_estimators': 609, 'learning_rate': 0.013174061999578166, 'max_depth': 9, 'subsample': 0.6744977259377715, 'colsample_bytree': 0.7597892353193294, 'min_child_weight': 2, 'gamma': 1.415033696284278}. Best is trial 10 with value: 5.6116268012458965.
[I 2026-06-27 09:19:35,497] Trial 17 finished with value: 5.664305892520568 and parameters: {'n_estimators': 576, 'learning_rate': 0.024580418520622246, 'max_depth': 9, 'subsample': 0.7240368145568469, 'colsample_bytree': 0.7530800824991247, 'min_child_weight': 1, 'gamma': 1.7040462682183442}. Best is trial 10 with value: 5.6116268012458965.
[I 2026-06-27 09:19:43,205] Trial 18 finished with value: 5.617069418134765 and parameters: {'n_estimators': 637, 'learning_rate': 0.036640826573214526, 'max_depth': 9, 'subsample': 0.6487365837436408, 'colsample_bytree': 0.6173482194254334, 'min_child_weight': 3, 'gamma': 1.3476377183247656}. Best is trial 10 with value: 5.6116268012458965.
[I 2026-06-27 09:19:52,472] Trial 19 finished with value: 5.69545697323161 and parameters: {'n_estimators': 880, 'learning_rate': 0.034803021873811915, 'max_depth': 8, 'subsample': 0.643630734254315, 'colsample_bytree': 0.9006539144087229, 'min_child_weight': 4, 'gamma': 2.5102540146848273}. Best is trial 10 with value: 5.6116268012458965.
[I 2026-06-27 09:20:03,426] Trial 20 finished with value: 5.920705064753439 and parameters: {'n_estimators': 520, 'learning_rate': 0.134013404408041, 'max_depth': 10, 'subsample': 0.6418352189089869, 'colsample_bytree': 0.7041220931624017, 'min_child_weight': 3, 'gamma': 0.5144597797148499}. Best is trial 10 with value: 5.6116268012458965.
[I 2026-06-27 09:20:11,848] Trial 21 finished with value: 5.601871503615901 and parameters: {'n_estimators': 648, 'learning_rate': 0.015416024442956193, 'max_depth': 9, 'subsample': 0.7262641750015835, 'colsample_bytree': 0.6018023498797467, 'min_child_weight': 2, 'gamma': 1.3108568771881817}. Best is trial 21 with value: 5.601871503615901.
[I 2026-06-27 09:20:19,824] Trial 22 finished with value: 5.596515520445669 and parameters: {'n_estimators': 675, 'learning_rate': 0.016077602281477466, 'max_depth': 9, 'subsample': 0.7227753914517264, 'colsample_bytree': 0.6160666739215565, 'min_child_weight': 2, 'gamma': 1.331194394015243}. Best is trial 22 with value: 5.596515520445669.
[I 2026-06-27 09:20:27,210] Trial 23 finished with value: 5.621139533000349 and parameters: {'n_estimators': 677, 'learning_rate': 0.01754886448496686, 'max_depth': 8, 'subsample': 0.7285685832485415, 'colsample_bytree': 0.6101430872286795, 'min_child_weight': 2, 'gamma': 2.2336793267591504}. Best is trial 22 with value: 5.596515520445669.
[I 2026-06-27 09:20:42,913] Trial 24 finished with value: 5.5870582120895875 and parameters: {'n_estimators': 856, 'learning_rate': 0.020148206559602352, 'max_depth': 10, 'subsample': 0.7475007635696106, 'colsample_bytree': 0.6456934819308223, 'min_child_weight': 1, 'gamma': 1.084835009652121}. Best is trial 24 with value: 5.5870582120895875.
[I 2026-06-27 09:20:54,644] Trial 25 finished with value: 5.597757132029319 and parameters: {'n_estimators': 895, 'learning_rate': 0.021324093940382864, 'max_depth': 9, 'subsample': 0.7470496988079699, 'colsample_bytree': 0.6303024709165105, 'min_child_weight': 4, 'gamma': 1.3649778451413062}. Best is trial 24 with value: 5.5870582120895875.
[W 2026-06-27 09:20:56,254] Trial 26 failed with parameters: {'n_estimators': 870, 'learning_rate': 0.021527142577928184, 'max_depth': 10, 'subsample': 0.7964443248856709, 'colsample_bytree': 0.6431930546416584, 'min_child_weight': 4, 'gamma': 2.3709613802377962} because of the following error: KeyboardInterrupt().
Traceback (most recent call last):
  File "c:\Users\Yosua Triantara\AppData\Local\Programs\Python\Python313\Lib\site-packages\optuna\study\_optimize.py", line 206, in _run_trial
    value_or_values = func(trial)
  File "C:\Users\Yosua Triantara\AppData\Local\Temp\ipykernel_27336\3138628287.py", line 58, in objective
    model.fit(
    ~~~~~~~~~^


    ...<3 lines>...


    )
    ^
  File "c:\Users\Yosua Triantara\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\core.py", line 553, in inner_f
    return func(**kwargs)
  File "c:\Users\Yosua Triantara\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\sklearn.py", line 1369, in fit
    self._Booster = train(
                    ~~~~~^
        params,
        ^^^^^^^
    ...<9 lines>...
        callbacks=self.callbacks,
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\Users\Yosua Triantara\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\core.py", line 553, in inner_f
    return func(**kwargs)
  File "c:\Users\Yosua Triantara\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py", line 200, in train
    bst.update(dtrain, iteration=i, fobj=obj)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Yosua Triantara\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\core.py", line 2203, in update
    _LIB.XGBoosterUpdateOneIter(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self.handle, ctypes.c_int(iteration), dtrain.handle
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
KeyboardInterrupt
[W 2026-06-27 09:20:56,284] Trial 26 failed with value None.

KeyboardInterrupt:

In [26]:
print(study.best_params)

{'n_estimators': 856, 'learning_rate': 0.020148206559602352, 'max_depth': 10, 'subsample': 0.7475007635696106, 'colsample_bytree': 0.6456934819308223, 'min_child_weight': 1, 'gamma': 1.084835009652121}

In [25]:
best_xgb = XGBRegressor(
    **study.best_params,
    objective="reg:squarederror",
    random_state=42,
    n_jobs=-1
)

X_train_final = np.vstack([X_train_xgb, X_val_xgb])
y_train_final = np.concatenate([residual_train, residual_val])

best_xgb.fit(
    X_train_final,
    y_train_final
)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.6456934819308223, device=None,
             early_stopping_rounds=None, enable_categorical=True,
             eval_metric=None, feature_types=None, feature_weights=None,
             gamma=1.084835009652121, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=0.020148206559602352,
             max_bin=None, max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=10, max_leaves=None,
             min_child_weight=1, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=856, n_jobs=-1,
             num_parallel_tree=None, ...)

In [27]:
# Prediksi residual menggunakan model terbaik
train_residual_pred = best_xgb.predict(X_train_xgb)
val_residual_pred   = best_xgb.predict(X_val_xgb)
test_residual_pred  = best_xgb.predict(X_test_xgb)

In [28]:
train_final = y_train_pred.ravel() + train_residual_pred
val_final   = y_val_pred.ravel() + val_residual_pred
test_final  = y_test_pred.ravel() + test_residual_pred

In [29]:
train_metrics = evaluate(y_train_true, train_final)
val_metrics   = evaluate(y_val_true, val_final)
test_metrics  = evaluate(y_test_true, test_final)

tuned_results = pd.DataFrame(
    [train_metrics, val_metrics, test_metrics],
    index=["Train", "Validation", "Test"]
)

tuned_results

                 MAE        MSE      RMSE     NRMSE        R2
Train       2.213165  15.759230  3.969790  0.003806  0.997878
Validation  1.923223  10.004096  3.162925  0.004800  0.998225
Test        2.387085  22.889397  4.784286  0.008164  0.988318

In [32]:
comparison = pd.DataFrame({
    "Baseline": results.loc["Test"],
    "Optuna": tuned_results.loc["Test"]
}).T

comparison

               MAE        MSE     NRMSE        R2      RMSE        R²
Baseline  2.431621  23.942780  0.008350       NaN  4.893136  0.987781
Optuna    2.387085  22.889397  0.008164  0.988318  4.784286       NaN

In [42]:
tuned_results = tuned_results.rename(columns={"R²": "R2"})
results = results.rename(columns={"R²": "R2"})

In [43]:
print(results.columns.tolist())
print(tuned_results.columns.tolist())

['MAE', 'MSE', 'RMSE', 'NRMSE', 'R2']
['MAE', 'MSE', 'RMSE', 'NRMSE', 'R2']

In [44]:
improvement = pd.Series({
    "MAE (%)": (
        (results.loc["Test", "MAE"] - tuned_results.loc["Test", "MAE"])
        / results.loc["Test", "MAE"]
    ) * 100,

    "RMSE (%)": (
        (results.loc["Test", "RMSE"] - tuned_results.loc["Test", "RMSE"])
        / results.loc["Test", "RMSE"]
    ) * 100,

    "R2 (%)": (
        (tuned_results.loc["Test", "R2"] - results.loc["Test", "R2"])
        / abs(results.loc["Test", "R2"])
    ) * 100
})

improvement

MAE (%)     1.831525
RMSE (%)    2.224535
R2 (%)      0.054424
dtype: float64

In [45]:
os.makedirs("../models", exist_ok=True)

joblib.dump(
    best_xgb,
    "../models/best_xgb_optuna.pkl"
)

print("Final XGBoost model berhasil disimpan.")

Final XGBoost model berhasil disimpan.

In [46]:
import json

with open("../models/best_xgb_params.json", "w") as f:
    json.dump(study.best_params, f, indent=4)

print("Best hyperparameters berhasil disimpan.")

Best hyperparameters berhasil disimpan.